create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  lead_number bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  vehicle_id uuid references public.vehicles(id) on delete set null,
  vehicle_slug text,
  intent text not null default 'general'
    check (intent in ('general','enquiry','test-drive','finance','trade-in')),
  status text not null default 'new'
    check (status in ('new','contacted','qualified','appointment','negotiating','won','lost')),
  priority text not null default 'normal'
    check (priority in ('low','normal','high','urgent')),
  customer_name text not null,
  email text,
  phone text,
  preferred_contact text not null default 'either'
    check (preferred_contact in ('email','phone','either')),
  message text,
  visitor_id uuid,
  session_id uuid,
  source_path text,
  referrer_host text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  country_code text,
  assigned_to uuid references public.profiles(id) on delete set null,
  first_contacted_at timestamptz,
  qualified_at timestamptz,
  appointment_at timestamptz,
  won_at timestamptz,
  lost_at timestamptz,
  lost_reason text
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_status_activity_idx on public.leads (status, last_activity_at desc);
create index if not exists leads_vehicle_created_idx on public.leads (vehicle_id, created_at desc) where vehicle_id is not null;
create index if not exists leads_visitor_created_idx on public.leads (visitor_id, created_at desc) where visitor_id is not null;
create index if not exists leads_assigned_status_idx on public.leads (assigned_to, status, last_activity_at desc) where assigned_to is not null;

create table if not exists public.lead_activities (
  id bigint generated always as identity primary key,
  lead_id uuid not null references public.leads(id) on delete cascade,
  occurred_at timestamptz not null default now(),
  kind text not null,
  note text,
  old_status text,
  new_status text,
  created_by uuid references public.profiles(id) on delete set null
);

create index if not exists lead_activities_lead_time_idx
  on public.lead_activities (lead_id, occurred_at desc);

alter table public.leads enable row level security;
alter table public.lead_activities enable row level security;

drop policy if exists "staff can read leads" on public.leads;
create policy "staff can read leads"
  on public.leads for select to authenticated
  using (private.is_staff());

drop policy if exists "staff can update leads" on public.leads;
create policy "staff can update leads"
  on public.leads for update to authenticated
  using (private.is_staff())
  with check (private.is_staff());

drop policy if exists "staff can read lead activities" on public.lead_activities;
create policy "staff can read lead activities"
  on public.lead_activities for select to authenticated
  using (private.is_staff());

drop policy if exists "staff can add lead activities" on public.lead_activities;
create policy "staff can add lead activities"
  on public.lead_activities for insert to authenticated
  with check (private.is_staff());

revoke insert, update, delete on public.leads from anon;
revoke insert, update, delete on public.lead_activities from anon;

create or replace function public.touch_lead()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
begin
  new.updated_at := now();
  new.last_activity_at := now();

  if new.status is distinct from old.status then
    if new.status = 'contacted' and new.first_contacted_at is null then
      new.first_contacted_at := now();
    elsif new.status = 'qualified' and new.qualified_at is null then
      new.qualified_at := now();
    elsif new.status = 'appointment' and new.appointment_at is null then
      new.appointment_at := now();
    elsif new.status = 'won' and new.won_at is null then
      new.won_at := now();
    elsif new.status = 'lost' and new.lost_at is null then
      new.lost_at := now();
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists leads_touch_trigger on public.leads;
create trigger leads_touch_trigger
before update on public.leads
for each row execute function public.touch_lead();

create or replace function public.log_lead_status_change()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if new.status is distinct from old.status then
    insert into public.lead_activities (
      lead_id, kind, old_status, new_status, created_by
    )
    values (
      new.id, 'status_change', old.status, new.status, auth.uid()
    );
  end if;

  if new.priority is distinct from old.priority then
    insert into public.lead_activities (
      lead_id, kind, note, created_by
    )
    values (
      new.id,
      'priority_change',
      'Priority changed from ' || old.priority || ' to ' || new.priority,
      auth.uid()
    );
  end if;

  return new;
end;
$$;

drop trigger if exists leads_status_activity_trigger on public.leads;
create trigger leads_status_activity_trigger
after update on public.leads
for each row execute function public.log_lead_status_change();

create or replace function public.submit_public_lead(
  p_customer_name text,
  p_email text,
  p_phone text,
  p_preferred_contact text,
  p_message text,
  p_intent text,
  p_vehicle_slug text,
  p_visitor_id uuid,
  p_session_id uuid,
  p_source_path text,
  p_referrer_host text,
  p_utm_source text,
  p_utm_medium text,
  p_utm_campaign text,
  p_utm_content text,
  p_utm_term text,
  p_country_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  v_vehicle_id uuid;
  v_id uuid;
  v_number bigint;
  v_intent text := lower(coalesce(nullif(trim(p_intent), ''), 'general'));
  v_contact text := lower(coalesce(nullif(trim(p_preferred_contact), ''), 'either'));
  v_email text := lower(nullif(trim(p_email), ''));
  v_phone text := nullif(trim(p_phone), '');
  v_name text := trim(coalesce(p_customer_name, ''));
begin
  if char_length(v_name) < 2 or char_length(v_name) > 120 then
    raise exception 'invalid_name';
  end if;

  if v_email is null and v_phone is null then
    raise exception 'contact_required';
  end if;

  if v_email is not null and (
    char_length(v_email) > 254 or
    v_email !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  ) then
    raise exception 'invalid_email';
  end if;

  if v_phone is not null and char_length(v_phone) > 40 then
    raise exception 'invalid_phone';
  end if;

  if v_intent not in ('general','enquiry','test-drive','finance','trade-in') then
    v_intent := 'general';
  end if;

  if v_contact not in ('email','phone','either') then
    v_contact := 'either';
  end if;

  if p_session_id is not null and (
    select count(*)
    from public.leads
    where session_id = p_session_id
      and created_at >= now() - interval '15 minutes'
  ) >= 5 then
    raise exception 'rate_limited';
  end if;

  if nullif(trim(p_vehicle_slug), '') is not null then
    select id into v_vehicle_id
    from public.vehicles
    where slug = trim(p_vehicle_slug)
    limit 1;
  end if;

  insert into public.leads (
    vehicle_id, vehicle_slug, intent, priority, customer_name, email, phone,
    preferred_contact, message, visitor_id, session_id, source_path,
    referrer_host, utm_source, utm_medium, utm_campaign, utm_content,
    utm_term, country_code
  )
  values (
    v_vehicle_id,
    nullif(trim(p_vehicle_slug), ''),
    v_intent,
    case when v_intent = 'test-drive' then 'high' else 'normal' end,
    left(v_name, 120),
    v_email,
    v_phone,
    v_contact,
    left(nullif(trim(p_message), ''), 3000),
    p_visitor_id,
    p_session_id,
    left(nullif(trim(p_source_path), ''), 500),
    left(nullif(trim(p_referrer_host), ''), 255),
    left(nullif(trim(p_utm_source), ''), 180),
    left(nullif(trim(p_utm_medium), ''), 180),
    left(nullif(trim(p_utm_campaign), ''), 180),
    left(nullif(trim(p_utm_content), ''), 180),
    left(nullif(trim(p_utm_term), ''), 180),
    left(nullif(trim(p_country_code), ''), 8)
  )
  returning id, lead_number into v_id, v_number;

  insert into public.lead_activities (lead_id, kind, note)
  values (v_id, 'created', 'Lead submitted from website');

  if p_visitor_id is not null and p_session_id is not null then
    perform public.record_analytics_event(
      p_visitor_id,
      p_session_id,
      'generate_lead',
      coalesce(nullif(trim(p_source_path), ''), '/contact'),
      nullif(trim(p_vehicle_slug), ''),
      jsonb_build_object('intent', v_intent, 'lead_number', v_number),
      p_referrer_host,
      p_utm_source,
      p_utm_medium,
      p_utm_campaign,
      p_utm_content,
      p_utm_term,
      null,
      null,
      null,
      null,
      null,
      null,
      p_country_code,
      null
    );
  end if;

  return jsonb_build_object('lead_id', v_id, 'lead_number', v_number);
end;
$$;

revoke all on function public.submit_public_lead(
  text,text,text,text,text,text,text,uuid,uuid,text,text,text,text,text,text,text,text
) from public;

grant execute on function public.submit_public_lead(
  text,text,text,text,text,text,text,uuid,uuid,text,text,text,text,text,text,text,text
) to anon, authenticated;
